# Generated by Django 4.2.30 on 2026-09-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField(db_index=True, help_text='Date and time of the event')),
                ('venue', models.CharField(max_length=200)),
                ('poster_image', models.ImageField(blank=True, help_text='Upload custom poster image', null=True, upload_to='event_posters/')),
                ('use_default_poster', models.BooleanField(default=False, help_text='Use general MCSC Logo as poster (instead of custom poster image)')),
                ('registration_link', models.URLField(blank=True, help_text='Link to external registration form if applicable', null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, null=True, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text="Mark as featured — shows a 'Featured' badge on the event card")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Additional event date')),
                ('time', models.TimeField(blank=True, help_text='Optional event time (12-hour format e.g. 02:20 PM)', null=True)),
                ('label', models.CharField(blank=True, help_text="Optional label e.g., 'Day 2' or 'Session 2'", max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_dates', to='events.event')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'event_date'], name='events_even_is_publ_442f37_idx'),
        ),
    ]
