# Generated by Django 4.2.30 on 2026-09-13 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Full news article content')),
                ('poster_image', models.ImageField(blank=True, help_text='Upload custom poster image for this news article', null=True, upload_to='news_posters/')),
                ('use_default_poster', models.BooleanField(default=False, help_text='Use general MCSC Logo as news poster (instead of custom poster image)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, null=True, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, help_text='Optionally link an event to share its poster image with this news post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='events.event')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news_attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='document', max_length=20)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='news.newspost')),
            ],
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['is_published', '-published_at'], name='news_newspo_is_publ_401ce7_idx'),
        ),
    ]
