# Generated by Django 4.2.30 on 2026-09-13 12:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academics', 'Academic & Curriculum'), ('facilities', 'Campus Facilities'), ('hostel', 'Hostel & Mess'), ('programs', 'Programs & Events'), ('general', 'General Concerns')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='grievance_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp', 'txt', 'zip', 'rar'])])),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-review', 'In Review'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievance_replies', to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='grievances.grievance')),
            ],
            options={
                'verbose_name_plural': 'Grievance Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reply_posted', 'Reply Posted'), ('status_changed', 'Status Changed')], max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='grievances.grievance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='grievances__user_id_fb0746_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['student', '-created_at'], name='grievances__student_d181a5_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status', '-created_at'], name='grievances__status_fa319e_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['category', '-created_at'], name='grievances__categor_611065_idx'),
        ),
    ]
