# Generated by Django 4.2.30 on 2026-09-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('points', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['-points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_mavelikoppam', models.BooleanField(default=False, help_text='Uses special Mavelikoppam point scale: 1st=10, 2nd=7, 3rd=5. Normal games: 1st=5, 2nd=3, 3rd=2.')),
                ('has_gender_categories', models.BooleanField(default=False, help_text='Enable if this game has separate results for Boys and Girls.')),
                ('image', models.ImageField(blank=True, help_text='Background image shown on the game card (uploaded to Supabase).', null=True, upload_to='onam_games/')),
                ('scheduled_date', models.DateField(blank=True, help_text='Date on which this game is scheduled (shown on the event card)', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order on events page')),
            ],
            options={
                'verbose_name': 'Onam Game',
                'verbose_name_plural': 'Onam Games',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_overall_winner', models.BooleanField(default=False, help_text='Check this box in admin to officially reveal the Overall Winner Department on the Live Scoreboard & Home Banner!', verbose_name='Show Overall Winner')),
                ('announcement_date', models.CharField(default='August 21, 2026', help_text='Date string shown when the winner announcement is still pending (e.g. August 21, 2026).', max_length=100)),
            ],
            options={
                'verbose_name': 'Onam Championship Setting',
                'verbose_name_plural': 'Onam Championship Settings',
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('', 'Open (No Gender Split)'), ('M', 'Boys'), ('F', 'Girls')], default='', help_text='Leave blank for open/non-gendered events. Set to Boys or Girls for gender-split events.', max_length=1)),
                ('position', models.PositiveSmallIntegerField(choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place')])),
                ('participant_name', models.CharField(blank=True, help_text='Optional — student name (can be left blank)', max_length=200)),
                ('department', models.ForeignKey(blank=True, help_text='Department the winner represents (determines points awarded)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results', to='onam.department')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='onam.onamgame')),
            ],
            options={
                'verbose_name': 'Game Result',
                'verbose_name_plural': 'Game Results',
                'ordering': ['game', 'gender', 'position'],
                'unique_together': {('game', 'position', 'gender')},
            },
        ),
    ]
